### ISSUE TITLE
[Bug] vl3-basic example is incorrectly converted into the dashboard graphical model

### ISSUE THREAD

**Issue by VitalyGushin** [networkservicemesh/cmd-dashboard-backend#4]
Example: https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/features/vl3-basic

Cause: nodes contain **interfaceConnection**-s without a "source"
Need to explain why such connections are added, fix it, and add validation/logging.

**Comment by denis-tingaikin** [comment]
Seems like done
